### ISSUE TITLE
Broken tailwindcss.min.css link

### ISSUE THREAD

**Issue by gabrielctn** [tailwindtoolbox/Help-Article#4]
This line breaks the page:
https://github.com/tailwindtoolbox/Help-Article/blob/cb63228898224deb7384be49ae88b81547a2aa9e/index.html#L10

Instead it should be:
`<link rel="stylesheet" href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" />`

**Comment by tailwindtoolbox** [comment]
Thanks @gabrielctn for the spot :)

Fixed now 👍
